# Generated by Django 2.0.1 on 2019-07-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('class_name', models.CharField(choices=[('2019MPFT-Aug5-Sep6', '2019MPFT-Aug5-Sep6')], max_length=100)),
                ('phone_no', models.IntegerField(default=0, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=100, null=True)),
                ('participation_training', models.CharField(choices=[('Yes', 'Yes'), ('No', 'NO'), ('Maybe', 'Maybe')], max_length=100, null=True)),
                ('core_join', models.CharField(choices=[('Yes', 'Yes'), ('No', 'NO'), ('Maybe', 'Maybe')], max_length=100, null=True)),
                ('hear', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Alumni', 'Alumni'), ('Event', 'Event'), ('Instagram', 'Instagram'), ('Moringa-Website', 'Moringa-Website'), ('Referall', 'Referall'), ('Google', 'Google'), ('Nairobi-Tech-Week', 'Nairobi-Tech-Week'), ('Other', 'Other')], max_length=100, null=True)),
                ('influence', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Alumni', 'Alumni'), ('Event', 'Event'), ('Instagram', 'Instagram'), ('Moringa-Website', 'Moringa-Website'), ('Referall', 'Referall'), ('Google', 'Google'), ('Nairobi-Tech-Week', 'Nairobi-Tech-Week'), ('Other', 'Other')], max_length=100, null=True)),
                ('pay', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True)),
                ('education', models.CharField(choices=[('High-School', 'High-School'), ('Diploma', 'Diploma'), ('Bachelor-Degree', 'Bachelor-Degree'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate'), ('Other', 'Other')], max_length=100, null=True)),
                ('article_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
