# Generated by Django 2.0.1 on 2019-07-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20190723_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stude',
            old_name='core_join',
            new_name='Are_you_interested_in_joining_Moringa_Core_after_Moringa_Prep',
        ),
        migrations.RenameField(
            model_name='stude',
            old_name='pay',
            new_name='Do_you_understand_that_you_need_to_pay_the_full_amount',
        ),
        migrations.RenameField(
            model_name='stude',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='stude',
            old_name='participation_training',
            new_name='Have_you_participated_in_a_Moringa_School_training_before',
        ),
        migrations.RenameField(
            model_name='stude',
            old_name='education',
            new_name='What_is_your_highest_level_of_education_completed',
        ),
        migrations.RenameField(
            model_name='stude',
            old_name='hear',
            new_name='Whcih_avenue_was_most_influential_in_joining_Moringa_School',
        ),
        migrations.RenameField(
            model_name='stude',
            old_name='influence',
            new_name='Where_did_you_hear_about_Moringa_School',
        ),
        migrations.RenameField(
            model_name='stude',
            old_name='phone_no',
            new_name='phone_Number',
        ),
    ]
