# Generated by Django 2.0.1 on 2019-07-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_student_is_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stude',
            name='phone_Number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
